### ISSUE TITLE
Paper Dynamic Feature Queue for Surveillance Face Anti-spoofing via Progressive Training

### ISSUE THREAD

**Issue by Holmes2002** [MouxiaoHuang/General_DL#1]
Hi, I'm student in Hanoi University of Sience and Technology. I want to ask you that can you share code for Dynamic Feature Queue for Surveillance Face Anti-spoofing via Progressive Training paper, which you wrote.
I just want to use this in school area. Hope that receive your response soon !

**Comment by MouxiaoHuang** [comment]
Thank you for reaching out and expressing interest in my paper. 

I would like to clarify that the research and development work for the project discussed in the paper was conducted during my tenure as an intern at Baidu. Consequently, the code and its associated intellectual property rights are the property of Baidu. Since I am no longer affiliated with Baidu, I unfortunately do not have access to the code, nor do I possess the authority to distribute it.

Nevertheless, I encourage you to contact Baidu's research department or reach out to the corresponding author listed in the paper for further assistance. They may be able to provide the support or resources you need for your academic pursuits.

I appreciate your understanding in this matter and wish you the very best in your studies and future research endeavors.
